### ISSUE TITLE
Błędy i propozycje od czasu wprowadzenia ostatniej poprawki remove firebase-admin module

### ISSUE THREAD

**Issue by Dawidmadryy1** [michaljaz/itemszop#78]
**BŁĘDY**

- [ ] Bugujący się napis "Dalej" w płatności na stronie "Wciśnij dalej aby przejść do płatności" - Przy kliknięciu przycisk ładuje się w nieskończoność pomimo dobrze skonfigurowanych danych o bramce płatności **-zgłaszający: Izaiashi#8065**
- [ ] Brak opcji przewinięcia w górę i w dół menu na stronie w wersji na telefonie - Nie można zjechać na dół aby np. utworzyć voucher na telefonie **-zgłaszający: Patryczeq#1477**
- [ ] Czasami buguje się customowy motyw **-zgłaszający: Patryczeq#1477**

**PROPOZYCJE UŻYTKOWNIKÓW (nie muszą zostać wprowadzone)**

- [ ] Bardziej szczegółowa edycja html/css na własnym hostingu
- [ ] Dodać więcej bram płatności
